name: SonarQube Analysis

description: |
  This composite action runs a SonarQube analysis on a project.

inputs:
  sonar-token:
    description: 'The SonarQube authentication token.'
    required: true
  project-key:
    description: 'The SonarQube project key.'
    required: true
  project-name:
    description: 'The SonarQube project name.'
    required: true
  project-version:
    description: 'The SonarQube project version.'
    required: true
  sources:
    description: 'The source code directory to be analyzed.'
    required: true


runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SonarQube Scanner
      run: |
        curl -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip -o sonar-scanner.zip
        unzip sonar-scanner.zip
        mv sonar-scanner-4.6.0.2311-linux sonar-scanner
        chmod +x sonar-scanner/bin/sonar-scanner

    - name: Run SonarQube Analysis
      run: |
        sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=$INPUT_PROJECT_KEY \
          -Dsonar.projectName=$INPUT_PROJECT_NAME \
          -Dsonar.projectVersion=$INPUT_PROJECT_VERSION \
          -Dsonar.sources=$INPUT_SOURCES \
          -Dsonar.host.url=https://your-sonarqube-url.com \
          -Dsonar.login=$INPUT_SONAR_TOKEN
